apiVersion: fleet.cattle.io/v1alpha1
kind: Bundle
metadata:
  creationTimestamp: '2024-11-21T22:26:22Z'
  finalizers:
    - fleet.cattle.io/bundle-finalizer
  generation: 40
  labels:
    fleet.cattle.io/commit: 710a5d85fdf9058a8f3cb5c66b76282d9fae7965
    fleet.cattle.io/repo-name: gitlab-tcu
    team: seint
  managedFields:
    - apiVersion: fleet.cattle.io/v1alpha1
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:finalizers:
            .: {}
            v:"fleet.cattle.io/bundle-finalizer": {}
      manager: fleetcontroller
      operation: Update
      time: '2024-12-26T23:15:40Z'
    - apiVersion: fleet.cattle.io/v1alpha1
      fieldsType: FieldsV1
      fieldsV1:
        f:status:
          .: {}
          f:conditions: {}
          f:display:
            .: {}
            f:readyClusters: {}
          f:maxNew: {}
          f:maxUnavailable: {}
          f:maxUnavailablePartitions: {}
          f:observedGeneration: {}
          f:partitions: {}
          f:resourceKey: {}
          f:resourcesSha256Sum: {}
          f:summary:
            .: {}
            f:desiredReady: {}
            f:ready: {}
          f:unavailable: {}
          f:unavailablePartitions: {}
      manager: fleetcontroller
      operation: Update
      subresource: status
      time: '2025-05-06T01:30:47Z'
    - apiVersion: fleet.cattle.io/v1alpha1
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:labels:
            .: {}
            f:fleet.cattle.io/commit: {}
            f:fleet.cattle.io/repo-name: {}
            f:team: {}
        f:spec:
          .: {}
          f:defaultNamespace: {}
          f:forceSyncGeneration: {}
          f:ignore: {}
          f:namespaceLabels:
            .: {}
            f:team: {}
          f:resources: {}
          f:targetRestrictions: {}
          f:targets: {}
      manager: fleet
      operation: Update
      time: '2025-05-23T22:28:05Z'
  name: solr-secret
  namespace: fleet-default
  resourceVersion: '645368682'
  uid: 94dfbe17-24d0-48c7-a55d-bb757d20e677
spec:
  defaultNamespace: solr
  forceSyncGeneration: 166
  ignore: {}
  namespaceLabels:
    team: seint
  resources:
    - content: |+
        defaultNamespace: solr
        namespaceLabels:
          team: seint
        labels:
          team: seint
        name: solr-secret

      name: fleet.yaml
    - content: |+
        apiVersion: external-secrets.io/v1beta1
        kind: SecretStore
        metadata:
          name: solr-secret-store
          namespace: solr
        spec:
          provider:
            vault:
              auth:
                kubernetes:
                  mountPath: kubernetes
                  role: solr
                  serviceAccountRef:
                    name: default
              path: rancher
              server: http://vault.vault:8200
              version: v2

      name: solr-secret-store.yaml
    - content: |+
        apiVersion: external-secrets.io/v1beta1
        kind: ExternalSecret
        metadata:
          name: solr-external-secret
          namespace: solr
        spec:
          secretStoreRef:
            name: solr-secret-store
            kind: SecretStore
          target:
            name: solr-usr-secret
          data:
            - remoteRef:
                key: prod
                property: solr_admin
              secretKey: solr-password

      name: solr-secret.yaml
  targetRestrictions:
    - clusterName: c-5wl22
  targets:
    - clusterName: c-5wl22
      ignore: {}
status:
  conditions:
    - lastUpdateTime: '2025-05-06T01:30:47Z'
      status: 'True'
      type: Ready
    - lastUpdateTime: '2024-12-26T23:07:47Z'
      status: 'True'
      type: Processed
  display:
    readyClusters: 1/1
  maxNew: 50
  maxUnavailable: 1
  maxUnavailablePartitions: 0
  observedGeneration: 40
  partitions:
    - count: 1
      maxUnavailable: 1
      name: All
      summary:
        desiredReady: 1
        ready: 1
  resourceKey:
    - apiVersion: external-secrets.io/v1beta1
      kind: SecretStore
      name: solr-secret-store
      namespace: solr
    - apiVersion: external-secrets.io/v1beta1
      kind: ExternalSecret
      name: solr-external-secret
      namespace: solr
  resourcesSha256Sum: 567b9b0b6766acab69239389d36c9a0ae20862a95384afb15654d3922b19568b
  summary:
    desiredReady: 1
    ready: 1
  unavailable: 0
  unavailablePartitions: 0
